name: PHP Composer

on:
  push:
    branches:
      - master
      - 'releases/**'
      - 'feature/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '8.2', '8.3', '8.4' ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Validate composer.json and composer.lock
        run: composer validate --strict -n

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.php-versions }}
          composer-options: --prefer-dist --no-scripts

      - run: composer crc
      - run: composer unuse

      - name: CS Check
        run: composer cs-check

      - name: PHPStan
        run: composer phpstan

      - name: PHPUnit
        run: composer phpunit
